const {
  rules: airbnbStyleRules,
} = require("eslint-config-airbnb-base/rules/style");
const {
  rules: airbnbImportsRules,
} = require("eslint-config-airbnb-base/rules/imports");

module.exports = {
  extends: [
    "eslint:recommended",
    "airbnb",
    "plugin:import/recommended",
    "plugin:import/typescript",
    "plugin:jest/recommended",
    "prettier",
  ],
  env: {
    es6: true,
  },
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    "no-underscore-dangle": "off",
    "no-plusplus": "off",
    "import/extensions": [
      "error",
      "ignorePackages",
      {
        js: "never",
        mjs: "never",
        jsx: "never",
        ts: "never",
        tsx: "never",
      },
    ],
    "import/no-extraneous-dependencies": [
      "error",
      {
        devDependencies: [
          ...airbnbImportsRules["import/no-extraneous-dependencies"][1]
            .devDependencies,
          "**/test/**",
          "**/*.test.[jt]sx",
          "configs/**",
          "**/next.config.js",
          "**/bin/**",
          "**/.storybook/preview.[jt]sx",
          "**/*.stories.tsx",
          "**/*.stories.jsx",
          "**/.storybook/main.js",
        ],
        optionalDependencies: false,
      },
    ],
    radix: "off",
    "max-len": [
      "warn",
      120,
      {
        ...airbnbStyleRules["max-len"][3],
        ignoreComments: true, // Ignore max-len rule for comments. It helps to have autogenerated JSDoc comments.
      },
    ],
    "react/jsx-filename-extension": ["error", { extensions: [".jsx", ".tsx"] }],
    "object-curly-newline": ["error", { multiline: true, consistent: true }],
  },
  overrides: [
    {
      files: ["*.ts", "*.tsx"],
      extends: ["plugin:@typescript-eslint/recommended"],
      rules: {
        "no-undef": "off", // Handled by typescript
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "no-shadow": "off",
        "@typescript-eslint/no-shadow": ["error"],
        "no-use-before-define": "off",
        "@typescript-eslint/no-use-before-define": [
          "warn",
          {
            functions: false,
            classes: false,
            variables: false,
            typedefs: false,
          },
        ],
      },
    },
    {
      files: ["*test.ts", "*test.data.ts"],
      plugins: ["jest"],
      rules: {
        "@typescript-eslint/no-explicit-any": "off",
        "import/no-extraneous-dependencies": [
          "error",
          {
            devDependencies: [
              "**/test/**",
              "**/*.test.[jt]sx",
              "**/*.test.[jt]s",
              "configs/**",
              "**/next.config.js",
              "**/bin/**",
              "**/.storybook/preview.[jt]sx",
              "**/*.stories.tsx",
              "**/*.stories.jsx",
              "**/.storybook/main.js",
            ],
            optionalDependencies: false,
          },
        ],
      },
    },
    {
      files: ["*.js", "*.jsx"],
      rules: {
        // We can't define types in js files
        "@typescript-eslint/explicit-module-boundary-types": "off",
      },
    },
  ],
};
